CPLP-1965 add checklist worker
catenax-ng/tx-portal-cd pull request #4
Opened 2023-01-12 12:08 UTC by Phil91

2023-01-12 14:37 UTC, evegufy commented on charts/portal/values.yaml
> +      checklistworkertag: "int-v0.6.0"
please add here also the v1.0.0-RC1 tag without quotes.

2023-01-12 14:47 UTC, evegufy commented on charts/portal/templates/secret-backend-portal-checklist.yaml
> +###############################################################
could you please remove the 'portal' from the file?
It's not a perfect rule but it's reasonable to assume that there won't be a checklist worker for provisioning so it's not need it.

2023-01-12 14:48 UTC, evegufy commented on charts/portal/templates/cronjob-backend-checklist.yaml
> +          restartPolicy: OnFailure
please add: concurrencyPolicy: Forbid

2023-01-12 14:49 UTC, evegufy requested changes
comments

2023-01-12 14:51 UTC, Phil91 commented on charts/portal/values.yaml
> +      checklistworkertag: "int-v0.6.0"
changed

2023-01-12 14:51 UTC, Phil91 commented on charts/portal/templates/secret-backend-portal-checklist.yaml
> +###############################################################
changed it to checklist-worker

2023-01-12 14:51 UTC, Phil91 commented on charts/portal/templates/cronjob-backend-checklist.yaml
> +          restartPolicy: OnFailure
added

2023-01-12 14:51 UTC, Phil91 commented
> comments

thanks for reviewing. isseus should be resolved

2023-01-19 11:53 UTC, evegufy requested changes

2023-01-19 12:10 UTC, Phil91 commented on charts/portal/values.yaml
> +      name: "ghcr.io/catenax-ng/product-portal-backend_checklist-worker"
changed :)

2023-01-19 12:24 UTC, evegufy approved these changes
lgtm, let's merge once https://github.com/catenax-ng/tx-portal-backend/pull/72 is ready

2023-01-20 08:34 UTC, merged