feature/CPLP-2341-regitration-documenttype-envsettings
catenax-ng/tx-portal-cd pull request #47
Opened 2023-03-16 07:09 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-2341

2023-03-16 07:16 UTC, evegufy requested changes
Please have a look at our commit and pr guidelines https://github.com/catenax-ng/tx-portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines
By now it's too late in this case to change the commit message but you still can adjust pr title and description according to the guidelines. Please do that. If you then do a squash commit at merge the pr title will be used as commit message.

2023-03-16 08:50 UTC, qxz2mqe commented
@evegufy Title is changed now

2023-03-16 09:19 UTC, evegufy commented
@qxz2mqe please also adjust the pr description, you already have ok nicely in the connected pr in the backend: https://github.com/catenax-ng/tx-portal-backend/pull/260

2023-03-16 11:57 UTC, evegufy approved these changes

2023-03-21 08:21 UTC, evegufy approved these changes

2023-03-21 08:33 UTC, merged