feat(offer): add companyAdminRoles to service & app
catenax-ng/tx-portal-cd pull request #84
Opened 2023-05-05 06:46 UTC by Phil91

Refs: CPLP-2521

2023-05-05 15:38 UTC, evegufy approved these changes

2023-05-11 12:31 UTC, ntruchsess requested changes

2023-05-11 12:31 UTC, ntruchsess commented on charts/portal/values.yaml
> +      role1: "Company Admin"
this should be 'role0', shouldn't it?

2023-05-11 12:35 UTC, Phil91 commented on charts/portal/values.yaml
> +      role1: "Company Admin"
right - fixed it.

2023-05-11 12:36 UTC, ntruchsess approved these changes

2023-05-11 12:43 UTC, ntruchsess requested changes

2023-05-11 12:43 UTC, ntruchsess commented on charts/portal/templates/deployment-backend-appmarketplace.yaml
> +        - name: "APPMARKETPLACE__COMPANYADMINROLES_Cl2-CX-Portal__0"
missing underscore after 'ROLES'

2023-05-11 12:46 UTC, Phil91 commented on charts/portal/templates/deployment-backend-appmarketplace.yaml
> +        - name: "APPMARKETPLACE__COMPANYADMINROLES_Cl2-CX-Portal__0"
Fixed

2023-05-11 12:46 UTC, ntruchsess approved these changes

2023-05-11 12:48 UTC, merged